CREATE TABLE customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL,
    phone TEXT,
    work_phone TEXT,
    phone_country TEXT,
    external_id TEXT,
    twitter TEXT,
    linkedin TEXT,
    timezone TEXT,
    language TEXT,
    address TEXT,
    about TEXT,
    notes TEXT,
    tag_ids UUID[],
    company_id UUID REFERENCES company(id),
    custom_fields JSONB,
    workspace_id UUID NOT NULL REFERENCES workspace(id),
    client_id UUID NOT NULL REFERENCES clients(id),
    created_by UUID NOT NULL REFERENCES users(id),
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);