const demoRequestRoute = require('./demoRequestRoutes');
const authRoute = require('./authRoutes');

const rolePermissionRoute = require('./rolePermissionRoute');
const roleRoute = require('./roleRoutes');
const workspaceRoute = require('./workspaceRoutes');
const workspaceSettingRoute = require('./workspaceSettingRoutes');
const profileRoute = require('./profileRoutes');
const userRoute = require('./userRoutes');
const clientRoute = require('./clientRoutes');
const ticketRoute = require('./ticketRoutes');
const conversationRoute = require('./conversationRoutes');
const customerRoute = require('./customerRoutes');
const companyRoute = require('./companyRoutes');
const ticketTopicRoutes = require('./ticketTopicRoutes');
const ticketStatusRoute = require('./ticketStatusRoutes');
const ticketTypeRoutes = require('./ticketTypeRoutes');
const tagRoutes = require('./tagRoutes');
const teamRoutes = require('./teamRoutes');
const chatbotProfileRoute = require('./chatbotProfileRoutes');
const chatbotDocumentRoute = require('./chatbotDocumentRoutes');
const contentFolderRoute = require('./contentFolderRoutes');
const mentionRoutes = require('./mentionRoutes');
const notificationRoute = require('./notificationRoutes');
const timelineRoutes = require('./timelineRoutes');

const customFieldRoute = require('./customFieldRoutes');
const customFieldDataRoute = require('./customFieldDataRoutes');
const customObjectFieldDataRoute = require('./customObjectFieldDataRoutes');
const workflowRoute = require('./workflowRoutes');
const aiToolRoute = require('./aiToolRoutes');
const cannedResponseRoute = require('./cannedResponseRoutes');
const webhookRoute = require('./webhookRoutes');
const reportRoute = require('./reportRoutes');
const customSupportEmailRoute = require('./customSupportEmailRoutes');
const emailDomainRoute = require('./emailDomainRoutes');
const eventWorkflowRoute = require('./eventWorkflowRoutes');
const emailTemplateRoute = require('./emailTemplateRoutes');
const workspacePermission = require('./workspacePermission');
const customObjectRoute = require('./customObjectRoutes');
const emailChannelsRoute = require('./emailChannelsRoutes');
const widgetRoute = require('./widgetRoutes');
const analyticsRoute = require('./analyticsRoutes');
const ablyRoute = require('./ablyRoutes');
const actionCenterRoute = require('./actionCenterRoutes');
const copilotProfileRoute = require('./copioltRoutes');
const copilotChatRoute = require('./copilotchatRoutes');
const preBuildActionRoute = require('./preBuildActions/index');
const channelRoute = require('./channelRoutes');
const pullseCrmRoute = require('./pullseCrmRoutes');

module.exports = {
  async activate(app) {
    await demoRequestRoute.activate(app);
    await workspaceRoute.activate(app);
    await workspaceSettingRoute.activate(app);
    await authRoute.activate(app);
    await rolePermissionRoute.activate(app);
    await roleRoute.activate(app);
    await profileRoute.activate(app);
    await userRoute.activate(app);
    await clientRoute.activate(app);
    await ticketRoute.activate(app);
    await conversationRoute.activate(app);
    await customerRoute.activate(app);
    await companyRoute.activate(app);
    await ticketTopicRoutes.activate(app);
    await ticketStatusRoute.activate(app);
    await ticketTypeRoutes.activate(app);
    await tagRoutes.activate(app);
    await teamRoutes.activate(app);
    await chatbotProfileRoute.activate(app);
    await chatbotDocumentRoute.activate(app);
    await contentFolderRoute.activate(app);
    await mentionRoutes.activate(app);
    await customFieldRoute.activate(app);
    await customFieldDataRoute.activate(app);
    await customObjectFieldDataRoute.activate(app);
    await workflowRoute.activate(app);
    await aiToolRoute.activate(app);
    await cannedResponseRoute.activate(app);
    await webhookRoute.activate(app);
    await reportRoute.activate(app);
    await customSupportEmailRoute.activate(app);
    await emailDomainRoute.activate(app);
    await eventWorkflowRoute.activate(app);
    await emailTemplateRoute.activate(app);
    await workspacePermission.activate(app);
    await customObjectRoute.activate(app);
    await emailChannelsRoute.activate(app);
    await widgetRoute.activate(app);
    await analyticsRoute.activate(app);
    await ablyRoute.activate(app);
    await notificationRoute.activate(app);
    await actionCenterRoute.activate(app);
    await copilotProfileRoute.activate(app);
    await timelineRoutes.activate(app);
    await copilotChatRoute.activate(app);
    await preBuildActionRoute.activate(app);
    await channelRoute.activate(app);
    await pullseCrmRoute.activate(app);
  }
};
