CREATE TABLE contactdevice (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contactId INT NOT NULL,
    publicIpAddress VARCHAR(255) NOT NULL,
    device VARCHAR(255) NOT NULL,
    operatingSystem VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP NULL
);
