CREATE TABLE customfielddata (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    customfieldId UUID NOT NULL,
    data TEXT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP,
);