CREATE TABLE tickets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sno INT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    entityType TEXT DEFAULT 'ticket',
    typeId TEXT,
    statusId TEXT,
    status TEXT DEFAULT 'open',
    customerId TEXT,
    sessionId TEXT,
    trackingId INT,
    externalId TEXT,
    language TEXT,
    priority INT DEFAULT 0,
    teamId TEXT,
    chatbotId TEXT,
    threadId TEXT,
    assigneeTo TEXT,
    assigneeId TEXT,
    companyId TEXT,
    topicIds TEXT[],
    tagIds TEXT[],
    mentionIds TEXT[],
    workspaceId TEXT NOT NULL,
    clientId TEXT NOT NULL,
    unread INT DEFAULT 0,
    lastMessage TEXT,
    lastMessageAt TIMESTAMP,
    lastMessageBy TEXT,
    channel TEXT,
    device TEXT,
    summary TEXT,
    intents JSONB,
    sentiment JSONB,
    reopen JSONB,
    qa JSONB,
    customFields JSONB,
    createdBy TEXT NOT NULL,
    ticketCreatedBy TEXT,
    closedAt TIMESTAMP,
    deletedAt TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE UNIQUE INDEX tickets_id_deletedAt_idx 
ON tickets (id, deletedAt);